# -*- coding: utf-8 -*-
"""Dio._.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ZZHurN4l950RRx8n4_Ddr7tvLhMqvPe
"""

menu = """ 
Qual operação deseja fazer?
[1] Deposiatr
[2] Sacar
[3] Extrato
[4] Sair
"""

saldo = 0
limite = 500
extrato = ''
numero_saques = 0
LIMITE_SAQUES = 3

while True:
    opcao = input(menu)

    if opcao == '1':
        valor = float(input('Digite o valor do deposito: '))

        if valor > 0:
            saldo += valor
            extrato += f'Deposito: R$ {valor:.2f}\n'
        else:
            print('Operaçao falhou! O valor é invalido.')
                
    elif opcao == '2':
        valor = float(input('Digite o valor do saque: '))

        saldo_ultrapassou = valor > saldo
        limite_ultrapassou = valor > limite
        saques_ultrapassou = numero_saques >= LIMITE_SAQUES

        if saldo_ultrapassou:
            print('Operaçao falhou! Você não tem saldo suficiente.')
        elif limite_ultrapassou:
            print('Operaçao falhou! O valor do saque ultrapassou o limite.')
        elif saques_ultrapassou:
            print('Operaçao falhou! Numero maximo de saque ultrapassou.')

        elif valor > 0:
            saldo -= valor
            extrato += f'Saque: R$ {valor:.2f}\n' 
            numero_saques += 1
        else:
            print('Operação falhou! O valor digitado é invalido.')

    elif opcao == '3':
        print('\n================= EXTRATO =================')
        print('Nao foram realizadas movimentações.' if not extrato else extrato)
        print(f'\nSaldo: R$ {saldo:.2f}')
        print('============================================')

    elif opcao == '4':
        break
    else:
        print('Operação inválida, por favor selecione novamente a operação desejada!')